#!/bin/bash -ex

if [[ -z $CI ]]; then
  ISORT_ARG=""
  BLACK_ARG=""
else
  ISORT_ARG="--check --diff"
  BLACK_ARG="--check"
fi

# format Python
black -l 80 $BLACK_ARG nnabla_browser
isort -l 80 --profile black $ISORT_ARG nnabla_browser

# format JS
npm run format
