#!/bin/bash -ex
# Copyright 2020,2021 Sony Corporation.
# Copyright 2021 Sony Group Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [[ -z $CI ]]; then
  ISORT_ARG=""
  BLACK_ARG=""
else
  ISORT_ARG="--check --diff"
  BLACK_ARG="--check"
fi

# format Python
black -l 80 $BLACK_ARG nnabla_browser
isort -l 80 --profile black $ISORT_ARG nnabla_browser

# format JS
npm run format
